language: cpp
dist: focal
before_install:
  - travis_retry sudo apt-get update -qq
install:
  - travis_retry sudo apt-get install scons
script: scons
branches:
  only:
    - master
compiler:
  - clang
  - gcc
