Import('env')

env.Substfile('README.in', SUBST_DICT = {'@PREFIX@': env['PREFIX']})
env.Substfile('SLM-inst.mk.in', SUBST_DICT = {
        '@DATADIR@': env['DATADIR'],
        '@ENDIANNESS@': env['ENDIANNESS']
    })

# -*- indent-tabs-mode: nil -*- vim:et:ts=4
